movieApp/urls.py
from django.urls import path, include
from . import views
app_name = 'movieApp'
urlpatterns = [

    path('',views.home,name='home'),
    path('movie/<int:movie_id>/',views.details,name='details'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieApp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                           document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieApp/models.py
from django.db import models


# Create your models here.
class movies(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery', default="")

    def __str__(self):
        return self.name

movieApp/forms.py
from django import forms
from .models import movies

class movieForm(forms.ModelForm):
    class Meta:
        model = movies
        fields = ['name','desc','year','img']

movieApp/views.py
from django.shortcuts import render, redirect

from . forms import movieForm
from . models import movies


# Create your views here.
def home(request):
    movie = movies.objects.all()
    context = {
        'movie_list': movie
    }
    return render(request, 'home.html', context)


def details(request, movie_id):
    movie = movies.objects.get(id=movie_id)
    return render(request, 'details.html', {'movie': movie})


def add_movie(request):
    if request.method == "POST":
        name = request.POST.get("name")
        desc = request.POST.get("desc")
        year = request.POST.get("year")
        img = request.FILES["img"]
        movie = movies(
            name=name,
            desc=desc,
            year=year,
            img=img
        )
        movie.save()
    return render(request, 'add.html')


def update(request, id):
    movie = movies.objects.get(id=id)
    form = movieForm(request.POST or None, request.FILES, instance=movie)

    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})
def delete(request,id):
    if request.method == 'POST':
        movie = movies.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
<title>Add</title>
{% extends 'base.html' %}
{% block body %}
<div class="container" style="margin-top:5rem;margin-left:35rem;">
    <div class="row">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="text" name="name" placeholder="Enter movie name"><br><br>
            <input type="text" name="desc" placeholder="Description"><br><br>
            <input type="text" name="year" placeholder="year"><br><br>
            <input type="file" name="img">
            <input type="submit" value="submit" class="btn-grad" href="/" style="width:7rem;">
            <a button type="button" class="btn-grad" href="/" style="width:7rem;">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="/" style="margin-left:20px;">

    Online moives hub
    <a href="add/" class="btn-grad">Add movies</a>
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
<title>Delete</title>
<form action="" method="post">
    {% csrf_token %}
    Are you sure want to delete this movie...?
    <input type="submit" value="Proceed">
</form>

templates/details.html
<title>Details</title>
{% extends 'base.html' %}
{% block body %}
<div class="container" style="margin-top:3rem;">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300">
        </div>
        <div class="col-md-6" style="color:white;">
            <h4>{{movie.name}}</h4>
             About :  <h6>{{movie.desc}}</h6>
             Released : {{movie.year}} <br><br>
            <a class="btn btn-warning" href="{% url 'movieApp:update' movie.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'movieApp:delete' movie.id %}">Delete</a>
            <a class="btn btn-primary" href="/">Home page</a>
        </div>
    </div>
</div>
{% endblock %}

templates/edit.html
<title>Modify</title>
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <form action="" method="post" enctype="multipart/form-data" style="color: white;">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="update">
            </form>
    </div>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block body %}

<div class="container" style="margin-top: 7px;">
    <div class="row">
        {% for mv in movie_list %}
        <div class="col-md-3 card-space">  
            <div class="card" style="width: 18rem;height: 459px;">
                <img src="{{mv.img.url}}"  width="100" height="200" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title" style="color: white;">{{mv.name}}</a></h5>
                  <p class="card-text" style="color: white;">{{mv.desc}}</p>
                  <a href="{% url 'movieApp:details' mv.id %}" class="btn-grad">View/Edit</a>
                  
                </div>
              </div>    
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}